---
# Configuration version, don't edit this.
config-version: 0.0.5

language: en-US

currency:
  name: USD
  symbol: $

  balance:
    default-balance: 0
    balance-cap: 1000 # Has no effect if enable-balance-cap is left false
    enable-balance-cap: false

  payment:
    minimum-payment: 10
    maximum-payment: 100

database:
  provider: sqlite

  mysql:
    host: 127.0.0.1
    username: root
    password: ""
    schema: ""
    port: 3306

  sqlite:
    data-file: players.db

  save-options:
    # instantaneous = 0
    # onDisconnection = 1
    # fixed period = 2
    save-mode: 1
    # Configuration for the "Fixed Period" update mode
    save-fixed-period: 3000
...
